import { parentPort } from "node:worker_threads";
import { inflateRawSync, inflateSync } from "node:zlib";
import yauzl from "yauzl";

const MAX_CHARS=200_000, MAX_STREAMS=128, MAX_INFLATED=2*1024*1024, MAX_TOTAL=8*1024*1024, MAX_ENTRIES=512, MAX_DOCX=12*1024*1024, MAX_XML=2*1024*1024;
const fail=(m:string):never=>{throw new Error(m);};
function bounded(v:string){const n=v.replace(/\r\n?/g,"\n").replace(/[\t ]+/g," ").trim();if(!n)fail("no text");return n.slice(0,MAX_CHARS);}
function pdfLiteral(v:string){return v.replace(/\\([nrtbf()\\]|[0-7]{1,3})/g,(_a,e:string)=>/^[0-7]/.test(e)?String.fromCharCode(Number.parseInt(e,8)):({n:"\n",r:"\r",t:"\t",b:"\b",f:"\f"} as Record<string,string>)[e]??e);}
function pdf(bytes:Uint8Array){const src=Buffer.from(bytes).toString("latin1");if(!src.startsWith("%PDF-")||src.includes("/Encrypt"))fail("pdf");const chunks:string[]=[];let pos=0,streams=0,total=0,length=0;while(pos<src.length&&length<MAX_CHARS){const at=src.indexOf("stream",pos);if(at<0)break;const before=src.charCodeAt(at-1),after=src.charCodeAt(at+6);if((before>32&&before!==62)||(after!==10&&after!==13)){pos=at+6;continue;}if(++streams>MAX_STREAMS)fail("streams");let start=at+6;if(src.charCodeAt(start)===13)start++;if(src.charCodeAt(start)===10)start++;const end=src.indexOf("endstream",start);if(end<0)fail("stream");const header=src.slice(Math.max(0,src.lastIndexOf("<<",at)),at);let body=Buffer.from(src.slice(start,end).replace(/\r?\n$/, ""),"latin1");if(body.length>MAX_INFLATED)fail("size");if(header.includes("/FlateDecode")){try{body=inflateSync(body,{maxOutputLength:MAX_INFLATED});}catch{try{body=inflateRawSync(body,{maxOutputLength:MAX_INFLATED});}catch{fail("inflate");}}}total+=body.length;if(total>MAX_TOTAL)fail("work");const text=body.toString("latin1");let p=0;while(p<text.length&&length<MAX_CHARS){const open=text.indexOf("(",p);if(open<0)break;let i=open+1,esc=false;for(;i<text.length;i++){const c=text.charCodeAt(i);if(esc){esc=false;continue;}if(c===92){esc=true;continue;}if(c===41)break;}if(i>=text.length)break;let j=i+1;while(j<text.length&&/\s/.test(text[j]!))j++;if(text.startsWith("Tj",j)||text[j]==="'"||text[j]==='"'){const value=pdfLiteral(text.slice(open+1,i));chunks.push(value);length+=value.length;}p=i+1;}pos=end+9;}return bounded(chunks.join(" "));}
function xmlDecode(v:string){if(/&(?!amp;|lt;|gt;|quot;|apos;|#\d+;|#x[\da-fA-F]+;)/.test(v))fail("entity");return v.replace(/&(?:amp|lt|gt|quot|apos);|&#(\d+);|&#x([\da-fA-F]+);/g,(e,d,h)=>e==="&amp;"?"&":e==="&lt;"?"<":e==="&gt;"?">":e==="&quot;"?'"':e==="&apos;"?"'":String.fromCodePoint(Number.parseInt(d||h,d?10:16)));}
function xmlText(xml:string){if(/<!DOCTYPE|<!ENTITY/i.test(xml))fail("dtd");const values:string[]=[];let p=0,len=0;while(p<xml.length&&len<MAX_CHARS){const open=xml.indexOf("<w:t",p);if(open<0)break;const boundary=xml[open+4];if(boundary!==">"&&boundary!=="/"&&boundary!==undefined&&!/\s/.test(boundary)){p=open+4;continue;}const gt=xml.indexOf(">",open+4);if(gt<0)fail("xml");const close=xml.indexOf("</w:t>",gt+1);if(close<0)fail("xml");const value=xmlDecode(xml.slice(gt+1,close));values.push(value);len+=value.length;p=close+6;}return bounded(values.join(" "));}
async function docx(bytes:Uint8Array):Promise<string>{return await new Promise((resolve,reject)=>yauzl.fromBuffer(Buffer.from(bytes),{lazyEntries:true,validateEntrySizes:true,decodeStrings:true,strictFileNames:true},(err,zip)=>{if(err||!zip)return reject(err??new Error());let count=0,total=0,xml:string|undefined,rels:string|undefined,done=false;const finish=(e?:unknown)=>{if(done)return;done=true;zip.close();e?reject(e):resolve(xmlText(xml??""));};zip.on("error",finish);zip.on("entry",entry=>{if(done)return;count++;total+=entry.uncompressedSize;const name=entry.fileName.replace(/\\/g,"/");if(count>MAX_ENTRIES||total>MAX_DOCX||entry.uncompressedSize>MAX_XML||name.startsWith("/")||name.split("/").includes(".."))return finish(new Error());if(name!=="word/document.xml"&&name!=="word/_rels/document.xml.rels")return zip.readEntry();zip.openReadStream(entry,(e,s)=>{if(e||!s)return finish(e??new Error());const parts:Buffer[]=[];let length=0;s.on("data",(part:Buffer)=>{length+=part.length;if(length>MAX_XML){s.destroy();finish(new Error());}else parts.push(part);});s.on("error",finish);s.on("end",()=>{if(done)return;const value=Buffer.concat(parts).toString("utf8");if(name==="word/document.xml")xml=value;else rels=value;zip.readEntry();});});});zip.on("end",()=>{if(/TargetMode\s*=\s*["']External["']/i.test(rels??""))return finish(new Error());if(!xml)return finish(new Error());finish();});zip.readEntry();}));}
parentPort?.on("message",async(m:{kind:"pdf"|"docx";bytes:Uint8Array})=>{try{parentPort?.postMessage({ok:true,text:m.kind==="pdf"?pdf(m.bytes):await docx(m.bytes)});}catch{parentPort?.postMessage({ok:false});}});
